version: "3.10"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=channel_service_orders
      - POSTGRES_USER=channel_service_admin
      - POSTGRES_PASSWORD=coolpas123
    expose:
      - 5432
  web:
    build: .
    command: >
      bash -c "python channel_service/manage.py makemigrations 
      && python channel_service/manage.py migrate 
      && cron
      && python channel_service/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=channel_service_orders
      - POSTGRES_USER=channel_service_admin
      - POSTGRES_PASSWORD=coolpas123
    depends_on:
      - db