# Generated by Django 4.1 on 2022-08-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('cost_usd', models.FloatField()),
                ('cost_rub', models.FloatField()),
                ('supply_date', models.DateField()),
            ],
        ),
    ]
